package br.com.timberforest.ratd.UteisDBPonsse;


import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by cicero.machado on 18/03/2016.
 */
public class DatabaseUtil extends SQLiteOpenHelper {

    //NOME DA BASE DE DADOS
    private static final String NOME_BASE_DE_DADOS   = "BD_PONSSE_TESTE.db";

    //VERSÃO DO BANCO DE DADOS
    private static final int    VERSAO_BASE_DE_DADOS = 2    ;

    //CONSTRUTOR
    public DatabaseUtil(Context context){

        super(context,NOME_BASE_DE_DADOS,null,VERSAO_BASE_DE_DADOS);
    }

    /*NA INICIALIZAÇÃO DA CLASSE VAMOS CRIAR A TABELA QUE VAMOS USAR*/
    @Override
    public void onCreate(SQLiteDatabase db) {

        StringBuilder stringBuilderCreateTable = new StringBuilder();

       /* stringBuilderCreateTable.append(" CREATE TABLE tb_garantia_forwarder (");
        stringBuilderCreateTable.append("        id_      INTEGER PRIMARY KEY AUTOINCREMENT,");
        stringBuilderCreateTable.append("        ds_telefone            TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_modelo              TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        dt_nascimento          TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_qtd_eixo            TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_qtd_hrs_revisao     TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_num_serie           TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_horas_motor         TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_ordem_servico       TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_cliente             TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        editText68    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText69    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText70    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText71    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText72    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText3     TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText136   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText146   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText147   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText149   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText150   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText151   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText152   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText38    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText39    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText40    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText41    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText42    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText43    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText44    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText45    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText46    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText47    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText48    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText49    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText50    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText51    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText56    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText57    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText58    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText59    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText154   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText153   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText155   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText156   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText157   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText158   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox140    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox209    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox210    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox211    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox213    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox214    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox215    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox216    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox217    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox218    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox264    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox265    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox266    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox267    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox268    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox269    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox270    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox271    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox272    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox273    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox274    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox275    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox276    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox277    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox278    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox279    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox280    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox281    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox284    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox285    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox286    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox287    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox288    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox289    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox290    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox291    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox292    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox293    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox294    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox295    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox296    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox297    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox298    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox299    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox55     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox56     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox57     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox58     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox59     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox60     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox103    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox104    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox105    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox106    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox107    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox108    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox109    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox110    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox111    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox112    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox113    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox114    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox115    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox116    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox300    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox301    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox302    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox303    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox304    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox305    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox306    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox307    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox308    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox309    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox310    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox311    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox312    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox313    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox314    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox315    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox316    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox317    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox318    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox319    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox320    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox321    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox322    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox323    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox324    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox325    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox326    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox327    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox328    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox329    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox330    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox333    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox334    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox335    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox336    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox337    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox338    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox339    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox340    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox341    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox342    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox343    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox344    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox345    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox346    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox347    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox348    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox349    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox350    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox351    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox352    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox353    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox354    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox355    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox356    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox357    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox358    INT    NOT NULL)            ");*/


        /*stringBuilderCreateTable.append(" CREATE TABLE tb_manutencaop_rogramada_grua (");
        stringBuilderCreateTable.append("         id_      INTEGER PRIMARY KEY AUTOINCREMENT,                       ");
        stringBuilderCreateTable.append("         ds_telefone            TEXT    NOT NULL,                          ");
        stringBuilderCreateTable.append("         fl_modelo              TEXT    NOT NULL,                          ");
        stringBuilderCreateTable.append("         dt_nascimento          TEXT    NOT NULL,                          ");
        stringBuilderCreateTable.append("         fl_num_serie           TEXT    NOT NULL,                          ");
        stringBuilderCreateTable.append("         fl_ordem_servico       TEXT    NOT NULL,                          ");
        stringBuilderCreateTable.append("         fl_cliente             TEXT    NOT NULL,                          ");

        stringBuilderCreateTable.append("         editText49ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText50ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText51ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editTextNotasForwarder            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText41ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText42ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText44ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText43ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText45ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText46ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText47ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText48ManuProgGrua            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup32BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup33BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup34BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup35BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup36BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup15BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup16BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup17BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup18BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup19BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup20BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup21BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup22BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup23BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup24BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup25BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup26BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup27BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup28BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup29BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup30BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup31BasicoManuProgGrua    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroupBasicCompManuProgGrua   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroupQtdEixoManuProgGrua     TEXT    NOT NULL,            ");

        stringBuilderCreateTable.append("         checkBoxVfslSelecionado           INT    NOT NULL,            ");
        stringBuilderCreateTable.append("         checkBoxVmvmgSelecionado          INT    NOT NULL,            ");
        stringBuilderCreateTable.append("         checkBoxTfsaappmiplSelecionado    INT    NOT NULL)             ");
*/



      /*  stringBuilderCreateTable.append(" CREATE TABLE tb_manu_prog_forw (");
        stringBuilderCreateTable.append("          id_                                        INTEGER PRIMARY KEY AUTOINCREMENT,");
        stringBuilderCreateTable.append("         ds_telefone                                 TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("         fl_modelo                                   TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("         dt_nascimento                               TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("         fl_qtd_eixo                                 TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("         fl_num_serie                                TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("         fl_ordem_servico                            TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         fl_cliente                                  TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText3NmManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText38NmManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText39NmManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editText40NmManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         editTextNotasForwarder                      TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup6ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup7ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup8ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup9ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup14ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup2ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup3ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup4ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup30ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup5ManuForwarder                    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroupBasicoCompManuForwarder           TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup13ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup31ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup10ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup20ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroup11ManuForwarder                   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("         radioGroupQtdeixoManuForwarder              TEXT    NOT NULL,            ");

        stringBuilderCreateTable.append("         checkBox505TarefasAdicioanisManuForwarder   INT    NOT NULL,            ");
        stringBuilderCreateTable.append("         checkBox237                                 INT    NOT NULL,            ");
        stringBuilderCreateTable.append("         checkBox238                                 INT    NOT NULL,              ");
        stringBuilderCreateTable.append("         checkBox239                                 INT    NOT NULL)               ");*/

       /* stringBuilderCreateTable.append(" CREATE TABLE tb_garantia_harvester (");
        stringBuilderCreateTable.append("        id_      INTEGER PRIMARY KEY AUTOINCREMENT,");
        stringBuilderCreateTable.append("        ds_telefone            TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_modelo              TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        dt_nascimento          TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_qtd_eixo            TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_qtd_hrs_revisao     TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_num_serie           TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_horas_motor         TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_ordem_servico       TEXT    NOT NULL,   ");
        stringBuilderCreateTable.append("        fl_cliente             TEXT    NOT NULL,   ");

        stringBuilderCreateTable.append("        editText159   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText6     TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText160   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText161   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText162   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText163   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText164   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText165   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText166   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText167   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText168   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText169   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText170   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText171   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText172   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText173   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText174   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText175   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText176   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText177   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText38    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText39    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText40    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText41    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText42    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText43    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText44    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText45    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText46    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText47    TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText178   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText179   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText180   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText181   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText182   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText183   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText184   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText185   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText186   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText187   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText188   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText189   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText190   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText191   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText192   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText193   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText194   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText195   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText196   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText197   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText198   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText199   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText200   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText201   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText202   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText203   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText204   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText205   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText206   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText207   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText208   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText209   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText210   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText211   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText212   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText213   TEXT    NOT NULL,            ");
        stringBuilderCreateTable.append("        editText214   TEXT    NOT NULL,            ");

        stringBuilderCreateTable.append("        checkBox4      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox5      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox6      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox7      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox8      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox9      INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox10     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox11     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox12     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox13     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox14     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox15     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox16     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox17     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox18     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox19     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox20     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox42     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox207    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox208    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox212    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox282    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox283    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox331    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox332    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox359    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox360    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox361    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox362    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox363    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox364    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox365    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox366    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox367    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox368    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox369    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox370    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox371    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox372    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox373    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox374    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox375    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox376    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox377    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox378    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox379    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox380    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox55     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox56     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox57     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox58     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox59     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox60     INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox103    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox104    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox105    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox106    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox107    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox108    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox109    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox110    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox111    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox112    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox113    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox114    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox115    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox116    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox381    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox382    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox383    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox384    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox385    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox386    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox387    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox388    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox389    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox390    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox391    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox392    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox393    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox394    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox395    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox396    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox397    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox398    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox399    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox400    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox401    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox402    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox403    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox404    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox405    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox406    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox407    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox408    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox409    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox410    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox411    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox412    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox413    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox414    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox415    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox416    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox417    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox418    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox419    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox420    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox421    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox422    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox423    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox424    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox425    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox426    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox427    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox428    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox429    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox430    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox431    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox432    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox433    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox434    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox435    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox436    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox437    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox438    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox439    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox440    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox441    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox442    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox443    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox444    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox445    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox446    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox447    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox448    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox449    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox450    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox451    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox452    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox453    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox454    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox455    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox456    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox457    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox458    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox459    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox460    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox461    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox462    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox463    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox464    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox465    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox466    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox467    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox468    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox469    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox470    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox471    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox472    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox473    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox474    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox475    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox476    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox477    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox478    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox479    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox480    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox481    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox482    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox483    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox484    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox485    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox486    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox487    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox488    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox489    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox490    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox491    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox492    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox493    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox494    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox495    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox496    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox497    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox498    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox499    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox500    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox501    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox502    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox503    INT    NOT NULL,            ");
        stringBuilderCreateTable.append("        checkBox504    INT    NOT NULL)            ");
*/


        db.execSQL(stringBuilderCreateTable.toString());

    }

    /*SE TROCAR A VERSÃO DO BANCO DE DADOS VOCÊ PODE EXECUTAR ALGUMA ROTINA
      COMO CRIAR COLUNAS, EXCLUIR ENTRE OUTRAS */
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

        //db.execSQL("DROP TABLE IF EXISTS tb_garantia_forwarder");
        db.execSQL("DROP TABLE IF EXISTS tb_manutencao_programada_grua");
        //db.execSQL("DROP TABLE IF EXISTS tb_manu_prog_forw");


        onCreate(db);

    }

    /*MÉTODO QUE VAMOS USAR NA CLASSE QUE VAI EXECUTAR AS ROTINAS NO
    BANCO DE DADOS*/
    public SQLiteDatabase GetConexaoDataBase(){

        return this.getWritableDatabase();
    }
}